[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
